synth.py
=> chore: add synth.py file

pom.xml, samples/install-without-bom/pom.xml, samples/snapshot/pom.xml, samples/snippets/pom.xml, versions.txt
also fixes the versions.txt so we can release this library
=> samples: fix versions

src/main/java/com/google/cloud/logging/logback/LoggingAppender.java, src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
=> feat: expose flush() method

pom.xml, versions.txt
This pull request was generated using releasetool.
Bump snapshot
=> chore: bump next snapshot

.repo-metadata.json, README.md
Fixes: https://github.com/googleapis/java-logging-logback/pull/96#discussion_r434106125
=> chore: fix and regenerate readme

.repo-metadata.json
Is this the correct link? I believe so but am not 100% certain.
=> chore: update client_documentation link

src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
=> chore: remove deprecated Class#newInstance() method

.github/CODEOWNERS, .repo-metadata.json
=> add api-logging to codeowners

src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
=> fix: logback logging exceptions with null message

.github/blunderbuss.yml
Adds back blunderbuss configs overridden by yoshi-automation bot
=> chore: add back blunderbuss configs overridden by yoshi-automation

pom.xml
=> deps: update api-commons

.github/auto-label.yaml
Enable staleness and pull request size auto-label bots on this repository
=> Enable staleness and pull request size bots on repository

.readme-partials.yaml
Add description for recently added (with #649 ) features.
=> chore: update readme with auto-population and redirect to stdout info

.github/auto-label.yaml, owlbot.py
Reenable staleness bot on the repo
=> fix: Reenable staleness bot

.kokoro/common.cfg, .kokoro/common_env_vars.cfg, .kokoro/continuous/common.cfg, .kokoro/nightly/common.cfg, .kokoro/presubmit/common.cfg, .kokoro/release/common.cfg, README.md, owlbot.py
This PR adds extra labels to the kokoro tests to make filtering easier for our test dashboards. It adds the following labels:
type: observability
product: logging
language: java
=> chore: added extra variables owlbot kokoro configs

.github/blunderbuss.yml
Update reviewers with googleapis/api-logging-reviewers
=> chore: Update blunderbuss with issues/pr reviewer

.github/release-please.yml, owlbot.py, src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
Fixes #[915](https://github.com/googleapis/java-logging-logback/issues/915) ☕️
=> feat: Add support for instrumentation version annotations

README.md
=> chore: fix release tag

.kokoro/build.sh, owlbot.py, pom.xml, src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-logging-logback/reflect-config.json
Logging-logback is part of the libraries BOM so this PR onboards this repo to have native image support.
=> fix(java): add native image configurations for logging-logback

.github/blunderbuss.yml, README.md
Fixes #<issue_number_goes_here> ☕️
=> chore(.github): Update logback issues and prs assignee

.github/CODEOWNERS, .repo-metadata.json
Fixes #<issue_number_goes_here> ☕️
=> chore: Update .repo-metadata.json and CODEOWNERS

.github/workflows/unmanaged_dependency_check.yaml
=> chore: add unmanaged dependency check

README.md
=> Doc: Suggest customers to not use this library if on cloud environments

pom.xml
BEGIN_COMMIT_OVERRIDE
deps: update dependency com.google.cloud:google-cloud-logging to v3.23.3
deps: update dependency com.google.cloud:sdk-platform-java-config to v3.52.0
END_COMMIT_OVERRIDE
=> chore: Updates deps for shared deps

.github/workflows/ci.yaml
Fixes #<issue_number_goes_here> ☕️
=> chore: add JDK 25 to the CI build
