googleapis/java-logging-logback

- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
> fix: logback error show in error reporting console

- .readme-partials.yaml
- README.md
- synth.py
> docs: generate readme from synth.py

- README.md
- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
fix: Documentation: version number and usage
Updated version number to latest release.
Improved documentation:
- Synced Javadoc and `README.md`, correcting error about filter in Javadoc
- Made example in Javadoc more easy to read and copy
Made 2 fields final to prevent editor/compiler warning.
Fixes #91
> fix: Documentation: version number and usage

- .readme-partials.yaml
- README.md
#92 fixed some usage examples in the README, but that content must be ported to .readme-partials.yaml so automation does not squash those changes.
> chore: migrate README changes to .readme-partials.yaml

- src/main/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancer.java
- src/test/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancerTest.java
With TraceLoggingEventEnhancer users can set the traceId of the incoming request and then all the logs that will be created on the same thread will have the traceId property set to that traceId. This allows Cloud Logging to group log entries from the same request in the UI for easier troubleshooting.
Example:
User's code (when receiving http request):
```java
TraceLoggingEnhancer.setCurrentTraceId(
"projects/" + GOOGLE_PROJECT_ID + "/traces/" + traceId);
```
Then just logging regularly:
```java
LOGGER.info("XXX");
```
Then use grouping by traceId in Cloud Logging:
Fixes #94 ☕️
> feat: adds support to group logs of the same http request

- src/main/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancer.java
- src/test/java/com/google/cloud/logging/logback/TraceLoggingEventEnhancerTest.java
Added cleanup of trace context before each test execution of tests that set it. This prevents side effects for other tests as a result of random ordering in junit.
Fixes #265 ☕️
Fixes #264 ☕️
Fixes #263 ☕️
> fix: Add cleanup for  Trace context

- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
The library takes in a FlushLevel argument, which defaults to ERROR. Any logs at that level or higher will be auto-flushed instead of batched.
It appears there is no way to turn the flush level off, forcing all logs to be batched. This PR checks for Level.OFF, and doesn't set the flush level if it is chosen
Fixes https://github.com/googleapis/java-logging-logback/issues/133 ☕️
> feat: allow flush level OFF

- README.md
> fix: update dead link

- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
To support unit testing auto-population logic, the setup of the monitored resource should do nothing if the variable is set.
> chore: fix unit tests

- README.md
- pom.xml
- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
This feature provides an ability to log extra entry with diagnostics structure which contains logging library information. Such entry is logged only once when first entry is written by a process using logging library.
Fixes #[<788>](https://github.com/googleapis/java-logging-logback/issues/788) ☕️
> feat: Add support for library instrumentation

- .readme-partials.yaml
- README.md
- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
Fixes #[598](https://github.com/googleapis/java-logging-logback/issues/598) ☕️
> feat: Add support for partialSuccess

- .github/CODEOWNERS
- .github/sync-repo-settings.yaml
Adding @googleapis/api-logging-partners to contain more people who can approve PRs
> fix: Add a partner team as approvers for PRs

- README.md
- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/main/java/com/google/cloud/logging/logback/MDCEventEnhancer.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
There are some changes that are not related to the functionality.
1. final keyword does not seem to be used consistently in test code.
2. final keyword is not required in the method of final class, so removed it.
3. Fixed some typos in javaDoc.
> chore: clean up final keyword and javaDoc typo

- .github/CODEOWNERS
Adding @googleapis/cloud-java-team-teamsync to CODEOWNERS for delegated client library release management.
> fix: update cloud-java-team as CODEOWNERS for delegated client release

- README.md
- pom.xml
Update these 2 dependencies together for dependency check to work together.
Closes #1119, #1117
> deps: update google-cloud-logging to v3.15.5, google-cloud-shared-dependencies to v3.12.0.

- .github/sync-repo-settings.yaml
- README.md
Manual configuration of the required check at Settings tab has been reverted. Adding that back via sync-repo-settings.yaml.
> ci: javadoc as a required check

- .github/workflows/unmanaged_dependency_check.yaml
- .kokoro/presubmit/graalvm-native-17.cfg
- .kokoro/presubmit/graalvm-native.cfg
- pom.xml
manual combine changes to avoid enforcer failures.
closes #1381
closes #1382
BEGIN_COMMIT_OVERRIDE
deps: update dependency com.google.cloud:google-cloud-logging to v3.20.4
deps: update dependency com.google.cloud:sdk-platform-java-config to v3.37.0
END_COMMIT_OVERRIDE
> deps: update dependency google-cloud-logging and sdk-platform-java-config

- pom.xml
- src/main/java/com/google/cloud/logging/logback/LogbackBatchingSettings.java
This PR introduces `java.time` alternatives to existing `org.threeten.bp.*` methods, as well as switching internal variables (if any) to `java.time`
The main constraint is to keep the changes backwards compatible, so for each existing threeten method "`method1(org.threeten.bp.Duration)`" we will add an alternative with a _Duration_ (or _Timestamp_ when applicable) suffix: "`method1Duration(java.time.Duration)`".
For most cases, the implementation will be held in the `java.time` method and the old threeten method will just delegate the call to it. However, for the case of abstract classes, the implementation will be kept in the threeten method to avoid breaking changes (i.e. users that already overloaded the method in their user code).
> feat: introduce `java.time`

- README.md
- samples/pom.xml
- src/main/java/com/google/cloud/logging/logback/LoggingAppender.java
- src/test/java/com/google/cloud/logging/logback/LoggingAppenderTest.java
- src/test/java/com/google/cloud/logging/logback/logback.xml
The java-logging library defaults to logging flush level to be OFF due to the performance cost of flushing on the same thread as the application. This fix is to change appender default flush level from `error` to be `off` to be consistent with java-logging library. For testing, added unit tests and changed existing easymock testing expectations.
Fixes #1328  ☕️
> Fix: Fix Appender default flushlevel to be consistent with java-logging

- README.md
> Doc: Add more explanation and examples for logbackBatchingSettings
